[package]
name = "nib-serde"
version = "0.2.2"
edition.workspace = true
rust-version.workspace = true
description = "JSON serialization types for Nib annotations"
authors.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
nib-core.workspace = true
serde.workspace = true
serde_json.workspace = true
